{
	"version": 1680969293,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/play-sheet0.png",
		"images/play-sheet1.png",
		"images/transição-sheet0.png",
		"images/transição2-sheet0.png",
		"images/grama-sheet0.png",
		"images/sky-sheet0.png",
		"images/player-sheet0.png",
		"images/camera-sheet0.png",
		"images/poçãodedabou-sheet0.png",
		"images/timer-sheet0.png",
		"images/bandeira-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/brasil-sheet0.png",
		"images/eua-sheet0.png",
		"images/anim_superpulo-sheet0.png",
		"images/anim_superpulo-sheet1.png",
		"images/anim_superpulo-sheet2.png",
		"images/anim_superpulooff-sheet0.png",
		"images/anim_superpulooff-sheet1.png",
		"media/mixkit-click-melodic-tone-1129.m4a",
		"media/mixkit-click-melodic-tone-1129.ogg",
		"media/menu principal_02.m4a",
		"media/menu principal_02.ogg",
		"media/menu principal.m4a",
		"media/menu principal.ogg",
		"media/clique.m4a",
		"media/clique.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"generator_config.txt",
		"hachicroundertalebattlefontregular-l3zlg-demo.html",
		"hachicroundertalebattlefontregular-l3zlg-webfont.woff",
		"hachicroundertalebattlefontregular-l3zlg-webfont.woff2",
		"stylesheet.css"
	]
}